#!/usr/bin/env php

<?php
/**
 * Generate a tree view of folders and files for current project
 *
 * Version 0.1
 *
 * CreatedBy: thang.tran@tiki.vn
 * Date: 10/18/15
 * Time: 7:09 PM
 */

define('PHPROOT', dirname(dirname(__FILE__)));

function createTreeView($structure, $initSymbol = '', &$text) {
    foreach($structure as $folderName => $subFolder) {
        $text .= $initSymbol . $folderName . ": *Docs for $folderName*" . PHP_EOL;
        createTreeView($subFolder, $initSymbol.'--', $text);
    }
}

function getStructure($rootPath, &$out) {
    if (is_dir($rootPath)) {
        $subDirs = scandir($rootPath);
        $baseName = basename($rootPath);
        $out[$baseName] = [];
        foreach ($subDirs as $subDir) {
            //ignore hidden folder
            if ($subDir[0] !== '.') {
                $subDirPath = $rootPath . '/' . $subDir;
                if (is_dir($subDirPath)) {
                    getStructure($subDirPath, $out[$baseName]);
                }
            }
        }
    }
}


$text = "" . PHP_EOL;
$out = [];
getStructure(PHPROOT, $out);
createTreeView($out, '', $text);
file_put_contents(dirname(PHPROOT) . '/README.md', $text, FILE_APPEND);
